### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by techkrtk** [potato-coin/react-native-potato-crypto#1]
<b>I am using the library in react-native 0.60.5 version<br />Its throwing the following error</b>

[40/40] Linking CXX shared library C:\Users\karth\Desktop\New\test\node_modules\react-native-potato-crypto\android\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so

> Task :app:transformNativeLibsWithStripDebugSymbolForDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
46 actionable tasks: 27 executed, 19 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> Could not read path 'C:\Users\karth\Desktop\New\test\android\app\build\intermediates\transforms\stripDebugSymbol\debug\0\lib\armeabi-v7a'.

**Comment by rise-worlds** [comment]
use gradle 4.4

**Comment by techkrtk** [comment]
> last test version 0.58, use gradle 4.4.

I have not installed gradle manually. It must be bundled with react-native. should i manually install 4.4.

thanks.
